---
title: "project-hack-vi"
author: "Phillip Abbott"
date: "June 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Organize the Monte Carlo Applications & Publish to Git

```{r}

library(tidyverse)

Rcpp::sourceCpp ("src/collapse.cpp")

xxx %>% sample_frac(.9) %>% cm0(999) %>% hist(breaks=29)

```

```{r}


xxx <- read.csv("src/xxx.csv")

cm0 <- function(it, n= 19)  collapse_many(n, it$b, it$e, it$w, it$p )

xxx %>% sample_frac(.9) %>% cm0(999) %>% hist(breaks=29)

rm(cm0)

 rm (xxx)



```



# testlib.do_mc(99)

py_print_array = testlib.print_array
py_print_array.argtypes = [ctl.ndpointer(np.float64, 
                                         flags='aligned, c_contiguous'), 
                           ctypes.c_int]
A = np.array([1.4,2.6,3.0, 1.1], dtype=np.float64)
py_print_array(A, 3)

print("\n\n")





```{python}

import ctypes
import numpy as np
import numpy.ctypeslib as ctl
import pandas as pd

xxx = pd.read_csv('src/xxx.csv')
Bx = np.array(xxx['b'], dtype=np.float64)
Ex = np.array(xxx['e'], dtype=np.float64)
Wx = np.array(xxx['w'], dtype=np.float64)
Px = np.array(xxx['p'], dtype=np.float64)

testlib = ctypes.CDLL('/home/phillip/Documents/stt/project-hack-vi/mcfc-xx/pysrc/testlib.so')

mcfc_collapse_all = testlib.py_collapse_all
mcfc_collapse_all.restype = ctypes.c_double
mcfc_collapse_all.argtypes = [ctypes.c_int,
                                ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), 
                                ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), 
                                ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), 
                                ctl.ndpointer(np.float64, flags='aligned, c_contiguous') ]

x0 = mcfc_collapse_all(99, Bx, Ex, Wx, Px);

print(x0);

```


# Py Months

```{python}

from ctypes import *

import numpy as np
import numpy.ctypeslib as ctl
import pandas as pd
  
testlib = CDLL('/home/phillip/Documents/stt/project-hack-vi/mcfc-xx/pysrc/testlib.so')


xxx = pd.read_csv('src/xxx.csv')
Bx = np.array(xxx['b'], dtype=np.float64)
Ex = np.array(xxx['e'], dtype=np.float64)
Wx = np.array(xxx['w'], dtype=np.float64)
Px = np.array(xxx['p'], dtype=np.float64)

  

testlib.py_months.argtypes = c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double),c_int, ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), ctl.ndpointer(np.float64, flags='aligned, c_contiguous'), ctl.ndpointer(np.float64, flags='aligned, c_contiguous')
testlib.py_months.restype = None


issues = (c_double*12)()
percent_50 = (c_double*12)()
percent_80 = (c_double*12)()
percent_95 = (c_double*12)()


testlib.py_months(12, issues, percent_50, percent_80, percent_95, 99, Bx, Ex, Wx, Px)

print(list(issues))
print(list(percent_50))
print(list(percent_80))
print(list(percent_95))


```














```{r}
library(tidyverse)

source("src/create_simulated_risks.R")

simulated_risks$get_some_sample_risks(9);

```



```{python}

import pandas as pd

xxx = pd.read_csv('src/xxx.csv')  

print(xxx['p'])

```









